# -*- coding: utf-8 -*-
"""A1P2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wao8AFKWr8EI1a4RxeWf2_BgjBSUHT1Q
"""

import torch
import torchtext

# The first time you run this will download a ~823MB file
glove = torchtext.vocab.GloVe(name="6B", # trained on Wikipedia 2014 corpus
                              dim=50)    # embedding size = 50

# category is a list of words
# word is the word and not the embedding of it

#Method 2
def compare_words_to_category(category,word):
  sum=0
  for item in category:
    sum+= glove[item]
  cat_measure=sum/len(category)
  return torch.cosine_similarity(cat_measure.unsqueeze(0), glove[word].unsqueeze(0))

#Method 1
def compare_words_to_category2(category,word):
  sum=0
  for item in category:
    sum+= torch.cosine_similarity(glove[item].unsqueeze(0), glove[word].unsqueeze(0))
  cat_measure=sum/len(category)
  return cat_measure